package hr.adriacomsoftware.app.client.smartgwt.evid.models;

public interface EvidencijaMjesecnaConstants {
	public static String EVIDMJ__RADNIK_ID = "radnik_id";
	public static String EVIDMJ__ID_SPICA_OJ = "id_spica_oj";
	public static String EVIDMJ__NAZIV = "naziv";
	public static String EVIDMJ__DATUM_OD = "datum_od";
	public static String EVIDMJ__DATUM_DO = "datum_do";
	public static String EVIDMJ__BROJ_DANA_RADA = "broj_dana_rada";
	public static String EVIDMJ__UKUPNI_BROJ_SATI = "ukupni_broj_sati";
	public static String EVIDMJ__SIF_01 = "sif_01";
	public static String EVIDMJ__SIF_01_10 = "sif_01_10";
	public static String EVIDMJ__SIF_03 = "sif_03";
	public static String EVIDMJ__SIF_10 = "sif_10";
	public static String EVIDMJ__SIF_12 = "sif_12";
	public static String EVIDMJ__SIF_23 = "sif_23";
	public static String EVIDMJ__SIF_09 = "sif_09";
	public static String EVIDMJ__SIF_01_11 = "sif_01_11";
	public static String EVIDMJ__SIF_01_12 = "sif_01_12";
	public static String EVIDMJ__SIF_01_13 = "sif_01_13";
	public static String EVIDMJ__SIF_27 = "sif_27";
	public static String EVIDMJ__SIF_01_5 = "sif_01_5";
	public static String EVIDMJ__SIF_02_2 = "sif_02_2";
	public static String EVIDMJ__SIF_14_2 = "sif_14_2";
	public static String EVIDMJ__SIF_14_1 = "sif_14_1";
	public static String EVIDMJ__SIF_01_3 = "sif_01_3";
	public static String EVIDMJ__SIF_15_2 = "sif_15_2";
	public static String EVIDMJ__SIF_01_32 = "sif_01_32";
	public static String EVIDMJ__SIF_01_30 = "sif_01_30";
	public static String EVIDMJ__SIF_01_31 = "sif_01_31";
	public static String EVIDMJ__SIF_14 = "sif_14";
	public static String EVIDMJ__SIF_01_6 = "sif_01_6";
	public static String EVIDMJ__SIF_15_1 = "sif_15_1";
	public static String EVIDMJ__SIF_01_99 = "sif_01_99";
	public static String EVIDMJ__SIF_12_1 = "sif_12_1";
	public static String EVIDMJ__SIF_11 = "sif_11";
	public static String EVIDMJ__SIF_15 = "sif_15";
	public static String EVIDMJ__SIF_17 = "sif_17";
	public static String EVIDMJ__SIF_22 = "sif_22";
	public static String EVIDMJ__SIF_01_1 = "sif_01_1";
	public static String EVIDMJ__SIF_01_2 = "sif_01_2";
	public static String EVIDMJ__SIF_27_2 = "sif_27_2";
	public static String EVIDMJ__SIF_03_2 = "sif_03_2";
	public static String EVIDMJ__SIF_01_71 = "sif_01_71";
	public static String EVIDMJ__SIF_01_72 = "sif_01_72";
	public static String EVIDMJ__SIF_12_2 = "sif_12_2";
	public static String EVIDMJ__SIF_18 = "sif_18";
	public static String EVIDMJ__SIF_01_4 = "sif_01_4";
	public static String EVIDMJ__SIF_12_3 = "sif_12_3";
	public static String EVIDMJ__SIF_01_8 = "sif_01_8";
	public static String EVIDMJ__SIF_15_0 = "sif_15_0";
	public static String EVIDMJ__SIF_12_0 = "sif_12_0";
	public static String EVIDMJ__SIF_12_4 = "sif_12_4";
	public static String EVIDMJ__SIF_23_1 = "sif_23_1";
	public static String EVIDMJ__SIF_999 = "sif_999";

	public static String EVIDMJ__MJESEC = "mjesec";
	public static String EVIDMJ__GODINA = "godina";
	
}